package dev.gbz.aoc2023.day21

object CornerFixture {
    //     .................
  //     .................
  //     .................
  //     z................
  //     yz...............
  //     xyz..............
  //     axyz.............
  //     xaxyz............
  //     axaxyz...........
  //     xaxaxyz..........
  //     axaxaxyz.........
  //     xaxaxaxyz........
  //     axaxaxaxyz.......
  //     xaxaxaxaxyz......
  //     axaxaxaxaxyz.....
  val fixture = Seq(
    3 -> Corner(0, 1, 3),
    4 -> Corner(1, 2, 4),
    5 -> Corner(2, 4, 5),
    6 -> Corner(4, 6, 6),
  )
}